### ISSUE TITLE
option to auto-import settings via json and minimize to tray/quiet mode

### ISSUE THREAD

**Issue by MerGr** [MrCoolAndroid/Xbox-Rich-Presence-Discord#124]
This program has been very useful for me while i use my Xbox 360 (I run it via Bottles (Wine)).

It would be very useful if the program can scan it's current directory for a 'settings.json' file that would auto populate all the settings needed, basically RPC is connected as soon as the program is started
```json
{"Settings" :[
  {"Gamertag:": "gamertag"}, 
  {"OXBL_API:": "api_key"}, 
 { "Ratelimit:": true}, 
  {"Device:": 0},
  {"Icon_method:": 0},
  {"SGDB_API:": "sgdb_api_key"}
]}
````
Device -> 0: Xbox 360, 1: Xbox One, 2: Xbox Series
Icon_method ->  0 : SGDB, 1: API, 2: GamesList.json
SGDB_API should be optional, if empty defaults to built in

would also be great to have the option to start quietly/without GUI, as it can be cleaner and, for my case, I can integrate with my Xbox 360 display script (I use a capture card hooked to my laptop) for seamless RPC.

**Comment by MrCoolAndroid** [comment]
These are very cool suggestions! I will look into implementing them soon! I never thought someone would use this app on Linux, or that it would work altogether, nice!

**Comment by MerGr** [comment]
Bottles makes it a lot easier to deploy

Xbox RPC bottle (Flatpak):
```yaml
Arch: win64
CompatData: ''
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.6.1
Environment: Application
Environment_Variables: {}
External_Programs:
    c228a6b1-c74a-43b1-bad1-cda08711ab7e:
        executable: Xbox Discord Presence.exe
        folder: $XDG_HOME/.XboxDiscordPresence
        id: c228a6b1-c74a-43b1-bad1-cda08711ab7e
        name: Xbox Discord Presence
        path: $XDG_HOME/.XboxDiscordPresence/Xbox Discord Presence.exe
Installed_Dependencies:
- arial32
- times32
- courie32
- mono
- gecko
- dotnetcoredesktop9
- dotnet481
- vbrun6
- dotnet35
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.9.0
Name: Xbox RPC
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: false
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mangohud_display_on_game_start: true
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: wine
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: Xbox-RPC
Runner: soda-9.0-1
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
VKD3D: vkd3d-proton-2.14.1
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
```

and these commands to enable RPC over Flatpak:

```
flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications  --filesystem=/home
flatpak override --system --filesystem=xdg-run/discord-ipc-*
```

After you setup the bottle with the appropriate shortcut leading to a valid location of the executable
Download the required .NET dependency installer and https://github.com/EnderIce2/rpc-bridge for wine RPC, and run both via Bottle's Install Program option and install them like you would on Windows.

![Image](https://github.com/user-attachments/assets/5dece6b8-a209-4fbd-9ef7-ed5162ae8ea1)
